/*
 * FixedMidashi JavaScript Library, version 1.5 (2014/08/12)
 * http://hp.vector.co.jp/authors/VA056612/fixed_midashi/
 * Copyright (C) 2012-2014 K.Koiso
 */

/* Exsample */
/*******************************************************************
<script type="text/javascript" src="hoge/fixed_midashi.js"></script>

<!-- body mode -->
<body onLoad="FixedMidashi.create();">
  <table _fixedhead="rows:1; cols:1">
    ...

<!-- div mode -->
<style type="text/css" media="screen">
  div.scroll_div { overflow: auto; }
</style>
<body onLoad="FixedMidashi.create();">
  <div class="scroll_div">
    <table _fixedhead="rows:1; cols:1">
      ...
*******************************************************************/

FixedMidashi = new function()
{
var DISABLED = false;

var ROWS = 1;
var COLS = 0;
var DIV_FULL_MODE = false;
var COPY_ID = true;
var BORDER_COLOR = null;
var BORDER_STYLE = null;
var BORDER_WIDTH = null;

var DIV_MIN_WIDTH = 150;
var DIV_MIN_HEIGHT = 150;

var RADIO_PREFIX = "_FIXED_HEADER_";

var POS_FIXED    = 1;
var POS_ABSOLUTE = 2;
var POS_MIX      = 3;
var _positionMode = -1;

var l="textarea",i="password",h="checkbox",f="select-multiple",e="select-one",g="change",k="radio",j="INPUT",Pb="sync",Ob="transparent",Nb="TD",Mb="0px",Lb="absolute",Kb="none",Jb="hidden",Ib="auto",Hb="",Gb="THEAD",Fb="scroll",o="resize",Eb=-1,Db=null,Cb=true,Bb=false,Ab=this;
var TIMER_WATCH_TABLESIZE=3e3,TID_HEADER="H",TID_NUMBER="N",TID_CORNER="C",PX="px",HEIGHT_MARGIN=10,MIN_SIZE=1,_isIE=Bb,_isIE8=Bb,_isIE11=Bb,_isFirefox=Bb,_isOpera=Bb,_isSafari=Bb,_isChrome=Bb,_isMobile=Bb,_isBackCompat=Bb,_fixedHeaders=Db,_fixedList=Db,_body=Db,_resizeTimerId=Db,_execFlag=Bb,_IE_retryCount=0;
Ab.create=function(){var f="_fixedhead";if(DISABLED)return Eb;if(!document.body.getBoundingClientRect)return -2;if(!window.addEventListener&&!window.attachEvent)return -3;var m=(new Date).getTime(),h=_fixedHeaders==Db;if(!h)for(var b=0;b<_fixedHeaders.length;b++)_fixedHeaders[b].removeAllTables(Bb);for(var i=document.body.getElementsByTagName("TABLE"),e=[],b=0;b<i.length;b++){var c=i[b],d=c.getAttribute(f);if(d==Db)d=c._fixedhead;if(d==undefined)continue;if(c.rows.length==0)continue;e.push(c)}if(e.length==0)return -4;var g=Db;if(h){var a=navigator.userAgent.toLowerCase();_isIE=a.indexOf("msie")>=0;if(_isIE){var j=a.indexOf("msie"),n=a.indexOf(";",j),l=Number(a.substring(j+5,n));_isIE8=l<=8}if(!_isIE)_isIE11=a.indexOf("trident")>=0;_isFirefox=a.indexOf("firefox")>=0;_isOpera=a.indexOf("opera")>=0;_isSafari=a.indexOf("safari")>=0&&a.indexOf("chrome")<0;_isChrome=a.indexOf("chrome")>=0;_isMobile=a.indexOf("mobile")>=0;if(_isIE&&_rect(i[0]).right>=1e4&&_IE_retryCount<10){setTimeout(FixedMidashi.create,10);_IE_retryCount++;return -5}_isBackCompat=document.compatMode=="BackCompat";_body=_isBackCompat?document.body:document.documentElement;if(_isIE&&_isBackCompat&&a.indexOf("msie 10.")<0)_positionMode=POS_ABSOLUTE;else if(_positionMode==Eb){_positionMode=POS_MIX;if(_isMobile)_positionMode=POS_FIXED}if(_isIE8&&!_isBackCompat)_fixedList=new _FixedElementList;if(_isFirefox)g=_createObjectForFirefox();_addEventListener(window,o,_onBodyResize);_isMobile&&_addEventListener(window,"orientationchange",_onBodyResize);(_isFirefox||_isSafari)&&!_isMobile&&TIMER_WATCH_TABLESIZE>=0&&setInterval(_checkZoom,TIMER_WATCH_TABLESIZE);_addEventListener(window,Fb,_onBodyScroll)}_fixedHeaders=[];for(var b=0;b<e.length;b++){var c=e[b],d=c.getAttribute(f);if(d==Db)d=c._fixedhead;var k=_createFixedHeader(c,d,e.length);_fixedHeaders.push(k)}_execute("init");h&&_createCSS("print",".fixed_header_display_none_at_print { display: none; visibility: hidden; }");g!=Db&&g.parentNode.removeChild(g);return (new Date).getTime()-m};
function _checkZoom(){if(_fixedHeaders==Db)return;for(var a=0;a<_fixedHeaders.length;a++)if(_fixedHeaders[a].checkZoom()){_execute(o);break}}
Ab.remove=function(){if(_fixedHeaders==Db)return;for(var a=0;a<_fixedHeaders.length;a++)_fixedHeaders[a].removeAllTables(Cb);_fixedHeaders=[]};
Ab.syncValue=function(a){if(_fixedHeaders==Db)return;if(!a)return;_copyValues(a)};
Ab.syncStyle=function(a,d){if(_fixedHeaders==Db)return;if(!a)return;if(_fixedList!=Db){var e=_fixedList.getAll(a);if(e==Db)return;for(var b=0;b<e.length;b++)_copyStyle(a,e[b],d);return}var c=a.$FXH_FIXED_ELEMENT;if(c==undefined)return;if(!c.$IS_ARRAY)_copyStyle(a,c,d);else for(var b=0;b<c.length;b++)_copyStyle(a,c[b],d)};
Ab.getFixedElement=function(b){if(_fixedHeaders==Db)return Db;if(!b)return Db;if(_fixedList!=Db)return _fixedList.get(b);var a=b.$FXH_FIXED_ELEMENT;if(!a)return Db;if(!a.$IS_ARRAY)return a;if(a.length==0)return Db;return a[a.length-1]};
Ab.getFixedElements=function(b){if(_fixedHeaders==Db)return Db;if(!b)return Db;if(_fixedList!=Db)return _fixedList.getAll(b);var a=b.$FXH_FIXED_ELEMENT;if(!a)return Db;if(a.$IS_ARRAY&&a.length==0)return Db;var c=[];if(!a.$IS_ARRAY)c.push(a);else for(var d=0;d<a.length;d++)c.push(a[d]);return c};
Ab.getSourceElement=function(a){if(_fixedHeaders==Db)return Db;if(!a)return Db;var b=a.$SOURCE_ELEMENT;return !b?Db:b};
Ab.isFixedElement=function(a){if(_fixedHeaders==Db)return Bb;if(!a)return Bb;return a.$SOURCE_ELEMENT!=undefined};
function _createFixedHeader(j,A,y){for(var v=j.rows,u=_cells(v[0]),o=0,e=0;e<u.length;e++)o+=u[e].colSpan;var d=ROWS,i=COLS,c=Eb,b=Eb,t=COPY_ID,f=BORDER_COLOR,g=BORDER_STYLE,h=BORDER_WIDTH,k=Db,l=1,p=DIV_FULL_MODE,w=_getElementByTagName(j,Gb);if(w!=Db)d=w.rows.length;for(var x=A.split(";"),e=0;e<x.length;e++){var q=x[e].split(":");if(q.length!=2)continue;var z=_trim(q[0]).toLowerCase(),a=_trim(q[1]);switch(z){case "rows":d=Number(a);break;case "cols":i=Number(a);break;case "div-max-width":c=_percent(a);break;case "div-max-height":b=_percent(a);break;case "div-full-mode":p=a.toLowerCase()=="yes";break;case "copyid":t=a.toLowerCase()=="yes";break;case "border-color":f=a;break;case "border-style":g=a;break;case "border-width":h=a;break;case "bgcolor":k=a;break;case "opacity":l=Number(a)}}if(d<0||d>=Math.min(v.length,11))d=0;if(i<0||i>=Math.min(o,11))i=0;if(!c||c<1||c>100)c=Eb;if(!b||b<1||b>100)b=Eb;if(y>1)p=Bb;if(l<0||l>1)l=1;var m=document.createElement("DIV");if(f!=Db&&!_setStyle(m,"borderColor",f))f=Db;if(g!=Db&&!_setStyle(m,"borderStyle",g))g=Db;if(h!=Db&&!_setStyle(m,"borderWidth",h))h=Db;if(k!=Db&&!_setStyle(m,"backgroundColor",k))k=Db;var s=Db;if(j.parentNode.tagName=="DIV"){var r=j.parentNode,n=r.currentStyle||document.defaultView.getComputedStyle(r,Hb);if(n.overflowX==Ib||n.overflowX==Fb||(n.overflowY==Ib||n.overflowY==Fb))s=r}return new _FixedHeader(s,j,o,d,i,c,b,p,t,f,g,h,k,l)}
function _onBodyScroll(){for(var a=0;a<_fixedHeaders.length;a++)_fixedHeaders[a].onBodyScroll()}
function _onBodyResize(){if(_execFlag)return;_resizeTimerId!=Db&&clearTimeout(_resizeTimerId);var a=function(){_execute(o)};
_resizeTimerId=setTimeout(a,200)}
function _execute(b){_execFlag=Cb;_resizeTimerId=Db;for(var a=0;a<_fixedHeaders.length;a++)if(b==o)_fixedHeaders[a].initOnResize();else _fixedHeaders[a].init();_resizeSourceDiv();for(var a=0;a<_fixedHeaders.length;a++)_fixedHeaders[a].main();_execFlag=Bb}
function _resizeSourceDiv(){for(var b=Bb,a=0;a<_fixedHeaders.length;a++)if(_fixedHeaders[a].hideAllDivs(Cb))b=Cb;if(!b)return;for(var a=0;a<_fixedHeaders.length;a++)_fixedHeaders[a].resizeSourceDiv1();var d=_body.style.overflowX,c=_body.currentStyle||document.defaultView.getComputedStyle(_body,Hb);if(_body.scrollWidth<=_body.clientWidth&&c.overflowX!=Fb)_body.style.overflowX=Jb;for(var a=0;a<_fixedHeaders.length;a++)_fixedHeaders[a].resizeDivHeight();for(var a=0;a<_fixedHeaders.length;a++)_fixedHeaders[a].resizeDivWidth();_body.style.overflowX=d;for(var a=0;a<_fixedHeaders.length;a++)_fixedHeaders[a].resizeSourceDiv2();for(var a=0;a<_fixedHeaders.length;a++)_fixedHeaders[a].hideAllDivs(Bb)}
function _FixedHeader(a,d,xb,q,y,v,z,jb,C,G,H,I,J,S){var m="CLIENT",u="visible",h="fixed",i="TBODY",g="1px",o=this,f=a!=Db,c=Db,b=Db,e=Db,eb=0,db=0,Y=Hb,X=Hb,L=Db,N=Db,B=[],kb=[],W=0,pb=d.style.zIndex?d.style.zIndex:0,p=Bb,x=Bb,j=0,l=0,nb=0,ob=0,V=0,U=0,Q=0,wb=d.style.display,Z=Eb,bb=Eb,k=Db,r=Eb,t=Eb,M=Db,K=Db;
o.init=function(){if(J==Db){var e=f?a:d,b=_getBackgroundColor(e);if(b==Db){var c=e.parentNode;while(c){b=_getBackgroundColor(c);if(b!=Db)break;if(c.tagName=="HTML")break;c=c.parentNode}if(b==Db)b="white"}J=b}if(f){_addEventListener(a,Fb,R);qb();Q=_offsetWidth(d)}ib()};
o.initOnResize=function(){t=Eb;r=Eb;bb=Eb;Z=Eb;if(f){if(p||v>0)a.style.width=Hb;if(x||z>0)a.style.height=Hb;Q=_offsetWidth(d)}ib()};
o.removeAllTables=function(d){c&&w(c);b&&w(b);e&&w(e);c=Db;b=Db;e=Db;if(f){_removeEventListener(a,Fb,R);if(d){if(p||v>0)a.style.width=Hb;if(x||z>0)a.style.height=Hb}}};
o.hideAllDivs=function(h){if(!f)return Bb;var d=c==Db?Db:c.parentNode,g=b==Db?Db:b.parentNode,j=e==Db?Db:e.parentNode;if(h){d&&F(d,DIV_MIN_WIDTH);g&&E(g,DIV_MIN_HEIGHT)}var i=h?Kb:Hb;if(d)d.style.display=i;if(g)g.style.display=i;if(j)j.style.display=i;(p||x||v>0||z>0)&&tb(h);if(h){p&&s(a,DIV_MIN_WIDTH);x&&A(a,DIV_MIN_HEIGHT)}return Cb};
o.resizeSourceDiv1=function(){if(!f)return;var e=k!=Db?k:d;if(v>0){j=_body.clientWidth/100*v;j=Math.max(j,DIV_MIN_WIDTH);var c=_offsetWidth(e)+V;c=Math.min(c,j);s(a,c)}if(z>0){l=_body.clientHeight/100*z;l=Math.max(l,DIV_MIN_HEIGHT);var b=_offsetHeight(e)+U;b=Math.min(b,l);A(a,b)}};
o.resizeDivHeight=function(){if(!f)return;if(!x)return;if(_body.scrollHeight>_body.clientHeight){var e=Math.max(_body.scrollHeight-_body.clientHeight,0);a.style.height=Math.max(_body.clientHeight-30,MIN_SIZE)+PX;var g=Math.max(_body.scrollHeight-_body.clientHeight,0);l=_offsetHeight(a)-(g-e)}else{a.style.height=_body.clientHeight+PX;var h=Math.max(_body.scrollHeight-_body.clientHeight,0);l=_offsetHeight(a)-h}l--;l=Math.max(l,DIV_MIN_HEIGHT);var c=k!=Db?k:d,b=_offsetHeight(c)+U;b=Math.min(b,l);if(jb)b=l;A(a,b)};
o.resizeDivWidth=function(){if(!f)return;if(!p)return;if(_body.scrollWidth>_body.clientWidth){var e=Math.max(_body.scrollWidth-_body.clientWidth,0);a.style.width=Math.max(_body.clientWidth-16,MIN_SIZE)+PX;var g=Math.max(_body.scrollWidth-_body.clientWidth,0);j=_offsetWidth(a)-(g-e)}else{a.style.width=_body.clientWidth+PX;var h=Math.max(_body.scrollWidth-_body.clientWidth,0);j=_offsetWidth(a)-h}j--;j=Math.max(j,DIV_MIN_WIDTH);var c=k!=Db?k:d,b=_offsetWidth(c)+V;b=Math.min(b,j);if(jb)b=j;if(_isIE)b--;s(a,b)};
o.resizeSourceDiv2=function(){if(!f)return;var b=k!=Db?k:d;if((p||v>0)&&a.scrollWidth>a.clientWidth&&_offsetWidth(a)<j){var e=a.scrollWidth-a.clientWidth,c=Math.min(_offsetWidth(a)+e,j),i=a.style.overflowY;if(_isIE)a.style.overflowY=Jb;s(a,c);if(_isIE)a.style.overflowY=i}if((x||z>0)&&a.scrollHeight>a.clientHeight&&_offsetHeight(a)<l){var e=a.scrollHeight-a.clientHeight,g=Math.min(_offsetHeight(a)+e,l);A(a,g)}if((p||v>0)&&Q>_offsetWidth(b)&&_offsetWidth(a)<j){var h=Q-_offsetWidth(b),c=Math.min(_offsetWidth(a)+h,j);s(a,c)}};
o.checkZoom=function(){if(Math.abs(_offsetWidth(d)-eb)>=1||Math.abs(_offsetHeight(d)-db)>=1||_colsWidthList(_cells(d.rows[0]))!=Y||_rowsHeightList(d.rows)!=X)return Cb};
o.main=function(){var h=_offsetWidth(d),g=_offsetHeight(d),b=eb!=h,a=db!=g;eb=h;db=g;var c=_colsWidthList(_cells(d.rows[0]));if(Y!=c){Y=c;b=Cb}var e=_rowsHeightList(d.rows);if(X!=e){X=e;a=Cb}var i=ub(b||a);(i||b||a)&&vb();f&&yb();if(f)R();else ab(Cb)};
function ub(l){if(l){c!=Db&&w(c);b!=Db&&w(b);e!=Db&&w(e);c=Db;b=Db;e=Db}var i=Bb,j=d.rows,k=f?d.parentNode:_body,h=Bb,g=Bb;if(f){h=a.clientHeight<a.scrollHeight&&a.clientHeight!=0;g=a.clientWidth<a.scrollWidth&&a.clientWidth!=0}else{h=_body.clientHeight<_body.scrollHeight;g=_body.clientWidth<_body.scrollWidth}if(q>0&&h)if(_rowsHeight(j,q)+30>=k.clientHeight)h=Bb;if(y>0&&g){var m=_cells(j[0]);if(_colsWidth(m,y)+30>=k.clientWidth)g=Bb}if(y>0&&g){if(b==Db){b=cb(TID_NUMBER,j.length,y);if(b!=Db)i=Cb}}else if(b!=Db){w(b);b=Db}if(q>0&&h){if(c==Db){c=cb(TID_HEADER,q,xb);if(c!=Db)i=Cb}}else if(c!=Db){w(c);c=Db}if(c!=Db&&b!=Db){if(e==Db){e=cb(TID_CORNER,q,y);i=Cb}}else if(e!=Db){w(e);e=Db}return i}
function vb(){if(c!=Db){s(c,_offsetWidth(d));T(c)}if(b!=Db){var g=_colsWidth(_cells(d.rows[0]),y),f=_colsWidth(_cells(b.rows[0]),y),a=f-g;a!=0&&s(b,_offsetWidth(b)-a);T(b);A(b,_offsetHeight(d))}if(e!=Db){s(e,_offsetWidth(b));T(e);A(e,_offsetHeight(c))}}
function yb(){var j=1,d=c==Db?Db:c.parentNode,f=b==Db?Db:b.parentNode,g=e==Db?Db:e.parentNode;d!=Db&&D(d);f!=Db&&D(f);g!=Db&&D(g);if(d!=Db){F(d,a.clientWidth);E(d,_offsetHeight(c));var i=_rect(c).bottom-_rect(d).bottom;i>0&&E(d,_offsetHeight(c)+i);d.clientHeight>=a.clientHeight&&E(d,a.clientHeight-j)}if(f!=Db){E(f,a.clientHeight);F(f,_offsetWidth(b));var h=_rect(b).right-_rect(f).right;h>0&&F(f,_offsetWidth(b)+h);f.clientWidth>=a.clientWidth&&F(f,a.clientWidth-j)}if(g!=Db){E(g,d.clientHeight);F(g,f.clientWidth)}}
function qb(){var b=a.cloneNode(Bb),c=d.cloneNode(Bb);b.style.position=Lb;b.style.left=Mb;b.style.top=Mb;b.style.minWidth=g;b.style.minHeight=g;a.parentNode.appendChild(b);var f=_rect(a),e=_rect(b);ob=f.top-e.top;nb=f.left-e.left;c.style.width="50px";c.style.height="50px";var h=document.createElement(i),k=document.createElement("TR"),j=document.createElement(Nb);j.appendChild(document.createTextNode("x"));k.appendChild(j);h.appendChild(k);c.appendChild(h);var m=b.offsetWidth,l=b.offsetHeight;b.appendChild(c);p=b.offsetWidth!=m;x=b.offsetHeight!=l;if(!p)v=Eb;if(!x)z=Eb;if(v>0)p=Bb;if(z>0)x=Bb;V=_offsetWidth(b)-_offsetWidth(c);U=_offsetHeight(b)-_offsetHeight(c);b.parentNode.removeChild(b)}
function ib(){if(q==0&&y==0)return;var a=d.cloneNode(Bb);a.style.position=Lb;a.style.left=Mb;a.style.top=Mb;a.style.width=Ib;a.style.height=Ib;a.width=Hb;a.height=Hb;var f,h=_getElementByTagName(d,Gb);if(h==Db)h=_getElementByTagName(d,i);if(h!=Db)f=h.cloneNode(Bb);else f=document.createElement(i);a.appendChild(f);d.parentNode.appendChild(a);for(var p=q>0?q:1,l=d.rows,m=0,c=0;c<p;c++){for(var o=l[c],n=o.cloneNode(Bb),g=_cells(o),e=0;e<g.length;e++){var k=g[e],b=k.cloneNode(Bb);b.width=Hb;if(k.colSpan==1)b.style.width=m+PX;else b.style.width=Ib;b.appendChild(document.createTextNode(" "));n.appendChild(b)}f.appendChild(n)}for(var c=0;c<p;c++)for(var g=_cells(l[c]),r=_cells(f.rows[c]),e=0;e<g.length;e++){var k=g[e],b=r[e];if(b.style.width==Ib)continue;var j=c+"."+k.cellIndex;kb[j]=_offsetWidth(b)-b.clientWidth;B[j]=b.clientWidth-m;W=Math.max(B[j],W)}a.parentNode.removeChild(a)}
function cb(e,s,t){var k=" fixed_header_display_none_at_print",c=d.cloneNode(Bb),o=_getElementByTagName(d,"CAPTION"),p=_getElementByTagName(d,Gb),r=_getElementByTagName(d,i),j=Db,m=Db,l=Db;if(o!=Db){j=o.cloneNode(Cb);j.style.backgroundColor=J;j.style.overflow=Jb;if(e!=TID_HEADER){j.innerHTML="&nbsp;";j.style.height=_offsetHeight(o)+PX;j.style.backgroundColor=Ob}c.appendChild(j)}var q=0;if(p!=Db){m=p.cloneNode(Bb);c.appendChild(m);q=p.rows.length}if(r!=Db&&q<s){l=r.cloneNode(Bb);c.appendChild(l)}if(zb(l,m,e,s,t,q)==Bb)return Db;_linkElement(c,d,e,C,Bb);j!=Db&&_linkElement(j,o,e,C,Cb);m!=Db&&_linkElement(m,p,e,C,Bb);l!=Db&&_linkElement(l,r,e,C,Bb);if(e!=TID_HEADER){c.style.marginRight=Mb;c.style.borderRightWidth=Mb;c.style.paddingRight=Mb}if(e!=TID_NUMBER){c.style.marginBottom=Mb;c.style.borderBottomWidth=Mb;c.style.paddingBottom=Mb}c.style.minWidth=g;c.style.minHeight=g;if(f){var b=a.cloneNode(Bb);b.$FXH_PADDING_WIDTH=undefined;b.$FXH_PADDING_HEIGHT=undefined;_linkElement(b,a,e,C,Bb);b.className+=k;b.style.overflowX=Jb;b.style.overflowY=Jb;_removeEventListener(b,Fb,R);e!=TID_CORNER&&_addEventListener(b,Fb,function(){sb(b,e)});if(e==TID_HEADER)b.style.borderRightWidth=Mb;else{b.style.marginRight=Mb;b.style.borderRightWidth=Mb;b.style.paddingRight=Mb}if(e==TID_NUMBER)b.style.borderBottomWidth=Mb;else{b.style.marginBottom=Mb;b.style.borderBottomWidth=Mb;b.style.paddingBottom=Mb}b.style.width="30px";b.style.height="30px";b.style.minWidth=g;b.style.minHeight=g;b.style.position=Lb;b.style.top=ob+PX;b.style.left=nb+PX;b.style.backgroundColor=J;b.appendChild(c);a.parentNode.appendChild(b)}else{c.className+=k;switch(_positionMode){case POS_FIXED:c.style.position=h;break;case POS_ABSOLUTE:c.style.position=Lb;break;default:c.style.position=h}c.style.marginTop=Mb;c.style.marginLeft=Mb;c.style.top=Mb;c.style.left=Mb;c.style.backgroundColor=J;d.parentNode.appendChild(c)}_isOpera&&n(f?b:c,Bb);return c}
function zb(n,o,g,s,p,u){for(var f=new Array(p),h=0;h<f.length;h++)f[h]=0;for(var t=d.rows,b=0;b<s;b++){var k=t[b],c=k.cloneNode(Bb);_linkElement(c,k,g,C,Bb);c.style.height=_trHeight(k)+PX;if(b==q-1&&g!=TID_NUMBER){if(G!=Db)c.style.borderBottomColor=G;if(H!=Db)c.style.borderBottomStyle=H;if(I!=Db)c.style.borderBottomWidth=I}if(g!=TID_HEADER)c.style.borderRightWidth=Mb;if(b<u)o.appendChild(c);else n.appendChild(c);for(var r=_cells(k),l=0,e=0;e<p;){if(b<f[e]){e++;continue}if(l>=r.length)break;var a=r[l];l++;if(b+a.rowSpan>s)return Bb;f[e]=b+a.rowSpan;if(a.colSpan>=2){for(var h=1;h<a.colSpan;h++)f[e+h]=f[e];if(e+a.colSpan>p)return Bb}_radioCtl(a,"backup");var j=a.cloneNode(Cb);_radioCtl(a,"restore");_linkElement(j,a,g,C,Cb);c.appendChild(j);try{var m=b+"."+a.cellIndex;if(B[m]!=undefined){var v=B[m]+kb[m];j.style.width=_offsetWidth(a)-v+PX}else if(_isIE8&&a.colSpan>1)j.style.width=a.clientWidth-W+PX}catch(w){}var i=j.style;if(b+a.rowSpan==q&&g!=TID_NUMBER){if(G!=Db)i.borderBottomColor=G;if(H!=Db)i.borderBottomStyle=H;if(I!=Db)i.borderBottomWidth=I}if(e+a.colSpan==y&&g!=TID_HEADER){if(G!=Db)i.borderRightColor=G;if(H!=Db)i.borderRightStyle=H;if(I!=Db)i.borderRightWidth=I}e+=a.colSpan}}o!=Db&&_radioCtl(o,Pb);n!=Db&&_radioCtl(n,Pb);return Cb}
function D(b){var f=_rect(a),e=_rect(b),d=e.top-f.top,c=e.left-f.left;if(_isIE){if(d==Eb&&b.$TOP_DIFF==1)d=0;else b.$TOP_DIFF=d;if(c==Eb&&b.$LEFT_DIFF==1)c=0;else b.$LEFT_DIFF=c}if(d!=0)b.style.top=_pixel(b.style.top)-d+PX;if(c!=0)b.style.left=_pixel(b.style.left)-c+PX}
function w(a){if(f)a=a.parentNode;_unlinkElement(a);a.parentNode.removeChild(a)}
o.onBodyScroll=function(){if(f)return;if(_positionMode==POS_ABSOLUTE){if(!_isMobile){if(_getBodyScrollTop()!=t){n(c,Bb);n(e,Bb)}if(_getBodyScrollLeft()!=r){n(b,Bb);n(e,Bb)}}M!=Db&&clearTimeout(M);M=setTimeout(ab,200)}else ab()};
function ab(j){M=Db;var i=_getBodyScrollTop()!=t,g=_getBodyScrollLeft()!=r;t=_getBodyScrollTop();r=_getBodyScrollLeft();if(i&&g)j=Cb;var f=_rect(d),m=c!=Db&&f.top<0&&f.bottom>=c.offsetHeight,o=b!=Db&&f.left<0&&f.right>=b.offsetWidth;c!=Db&&n(c,m);b!=Db&&n(b,o);e!=Db&&n(e,m&&o);if(_positionMode==POS_MIX&&c!=Db){var a=c.style;if(j||i&&a.position==Lb){a.position=h;a.left=f.left+PX;a.top=Mb;O(Bb)}else if(!i&&g&&a.position==h){a.position=Lb;a.left=r+f.left+PX;a.top=t+PX;hb()}}if(_positionMode==POS_MIX&&b!=Db){var a=b.style;if(j||g&&a.position==Lb){a.position=h;a.left=Mb;a.top=f.top+PX;P(Bb)}else if(!g&&i&&a.position==h){a.position=Lb;a.top=t+f.top+PX;a.left=r+PX;gb()}}if(_positionMode==POS_FIXED){if(c!=Db&&g)c.style.left=f.left+PX;if(b!=Db&&i)b.style.top=f.top+PX}if(_positionMode==POS_ABSOLUTE&&j){if(c!=Db)c.style.left=r+f.left+PX;if(b!=Db)b.style.top=t+f.top+PX}if(_positionMode==POS_ABSOLUTE&&(i||g)){var l,k,p=_isMobile?1:4;if(c!=Db&&i){c.style.top=t-_offsetHeight(c)+PX;if(e!=Db)e.style.top=c.style.top;l=(t-_pixel(c.style.top))/p}if(b!=Db&&g){b.style.left=r-_offsetWidth(b)+PX;if(e!=Db)e.style.left=b.style.left;k=(r-_pixel(b.style.left))/p}K!=Db&&clearTimeout(K);fb(i,g,l,k)}c!=Db&&g&&O(Bb);b!=Db&&i&&P(Bb)}
function fb(k,i,j,h){K=Db;var g=_getBodyScrollTop(),f=_getBodyScrollLeft(),d=g,a=f;if(c!=Db&&k){d=_pixel(c.style.top)+j;if(j>0)d=Math.min(d,g);else d=Math.max(d,g);c.style.top=d+PX;if(e!=Db)e.style.top=c.style.top}if(b!=Db&&i){a=_pixel(b.style.left)+h;if(h>0)a=Math.min(a,f);else a=Math.max(a,f);b.style.left=a+PX;if(e!=Db)e.style.left=b.style.left}if(g==d&&f==a){if(c!=Db&&k){hb();if(e!=Db)e.style.top=c.style.top}if(b!=Db&&i){gb();if(e!=Db)e.style.left=b.style.left}return}var l=function(){fb(k,i,j,h)};
K=setTimeout(l,20)}
function R(){var d=c==Db?Db:c.parentNode,f=b==Db?Db:b.parentNode,g=e==Db?Db:e.parentNode;n(d,a.scrollTop>0);n(f,a.scrollLeft>0);n(g,a.scrollTop>0&&a.scrollLeft>0);d!=Db&&D(d);f!=Db&&D(f);g!=Db&&D(g);var h=a.scrollLeft!=Z,i=a.scrollTop!=bb;Z=a.scrollLeft;bb=a.scrollTop;if(d!=Db&&h){d.$FXH_SCROLL_LEFT=a.scrollLeft;d.scrollLeft=a.scrollLeft;d.scrollLeft>0&&O(Bb)}if(f!=Db&&i){f.$FXH_SCROLL_TOP=a.scrollTop;f.scrollTop=a.scrollTop;f.scrollTop>0&&P(Bb)}}
function sb(b,c){if(c==TID_HEADER){if(Math.abs(b.scrollLeft-b.$FXH_SCROLL_LEFT)<1)return;if(Math.abs(b.scrollLeft-a.scrollLeft)<1)return}else{if(Math.abs(b.scrollTop-b.$FXH_SCROLL_TOP)<1)return;if(Math.abs(b.scrollTop-a.scrollTop)<1)return}if(c==TID_HEADER)a.scrollLeft=b.scrollLeft;else a.scrollTop=b.scrollTop}
function hb(){if(c==Db)return;var a=_rect(c);if(a.top<=0)return;c.style.top=_pixel(c.style.top)-a.top+PX}
function gb(){if(b==Db)return;var a=_rect(b);if(a.left<=0)return;b.style.left=_pixel(b.style.left)-a.left+PX}
function O(p){if(c==Db)return;if(!p){L!=Db&&clearTimeout(L);L=setTimeout(function(){O(Cb)},200);return}L=Db;var g,j;if(f){g=_rect(a).left;j=g+a.clientWidth}else{g=0;j=_body.clientWidth}if(b!=Db&&b.style.visibility==u)g+=_offsetWidth(b);for(var m=_cells(d.rows[0]),n=_cells(c.rows[0]),e=0,l=0,h=0;h<m.length;h++){var k=_rect(m[h]).left;if(k<g)continue;if(k>j)break;var o=_rect(n[h]).left;e+=o-k;l++}if(l==0)return;if(e==0)return;e=e/l;if(e==0)return;if(f){var i=c.parentNode;i.$FXH_SCROLL_LEFT=i.scrollLeft+e;i.scrollLeft+=e}else{var q=_pixel(c.style.left)-e;c.style.left=q+PX}}
function P(o){if(b==Db)return;if(_isOpera)return;if(!o){N!=Db&&clearTimeout(N);N=setTimeout(function(){P(Cb)},200);return}N=Db;var g,j;if(f){g=_rect(a).top;j=g+a.clientHeight}else{g=0;j=_body.clientHeight}if(c!=Db&&c.style.visibility==u)g+=_offsetHeight(c);for(var n=d.rows,m=b.rows,e=0,l=0,h=0;h<n.length;h++){var k=_rect(n[h]).top;if(k<g)continue;if(k>j)break;if(_cells(m[h]).length==0)continue;var p=_rect(m[h]).top;e+=p-k;l++}if(l==0)return;if(e==0)return;e=e/l;if(e==0)return;if(f){var i=b.parentNode;i.$FXH_SCROLL_TOP=i.scrollTop+e;i.scrollTop+=e}else{var q=_pixel(b.style.top)-e;b.style.top=q+PX}}
function n(a,b){if(a==Db)return;var c=b?u:Jb;if(a.style.visibility==c)return;a.style.visibility=c;if(_isIE)a.style.zIndex=b?pb+1:pb-1;if(_isOpera)a.style.opacity=b?S:0;if(b&&S<1){a.style.opacity=S;a.style.filter="alpha(opacity="+S*100+")"}}
function tb(b){if(!_isIE&&!_isIE11&&!_isFirefox&&!_isOpera)return;if(b){k=rb();a.appendChild(k);s(k,_offsetWidth(d));A(k,_offsetHeight(d));d.style.display=Kb}else{d.style.display=wb;a.removeChild(k);k=Db}}
function rb(){var a=d.cloneNode(Bb),b=document.createElement(i),e=document.createElement("TR"),c=document.createElement(Nb);c.appendChild(document.createTextNode("dummy"));e.appendChild(c);b.appendChild(e);a.appendChild(b);return a}
function F(a,b){mb(a,m,b)}
function s(a,b){mb(a,"OFFSET",b)}
function E(a,b){lb(a,m,b)}
function A(a,b){lb(a,"OFFSET",b)}
function mb(a,g,f){var b=f;if(a.$FXH_PADDING_WIDTH!=undefined)b-=a.$FXH_PADDING_WIDTH;for(var d,c,e=0;e<2;e++){if(b<MIN_SIZE)b=MIN_SIZE;a.style.width=b+PX;d=g==m?a.clientWidth:_offsetWidth(a);c=d-f;if(a.$FXH_PADDING_WIDTH==undefined)a.$FXH_PADDING_WIDTH=c;if(c==0||b==MIN_SIZE)break;b-=c}}
function lb(a,g,e){var b=e;if(a.$FXH_PADDING_HEIGHT!=undefined)b-=a.$FXH_PADDING_HEIGHT;for(var d,c,f=0;f<2;f++){if(b<MIN_SIZE)b=MIN_SIZE;a.style.height=b+PX;d=g==m?a.clientHeight:_offsetHeight(a);c=d-e;if(a.$FXH_PADDING_HEIGHT==undefined)a.$FXH_PADDING_HEIGHT=c;if(c==0||b==MIN_SIZE)break;b-=c}}
function T(p){var g=d.rows,c=p.rows,e=c.length,k=_rowsHeight(g,e)+HEIGHT_MARGIN;if(_rowsHeight(c,e)<k)return;for(var a=0;a<e;a++){var q=_trHeight(c[a])-_trHeight(g[a]);if(q<HEIGHT_MARGIN)continue;for(var o=_cells(g[a]),j=_cells(c[a]),f=0;f<j.length;f++){var l=o[f],i=j[f],b=0,h=a+"."+l.cellIndex;if(B[h]!=undefined){if(B[h]<=0)continue;b=B[h]-2;if(b<0)b=0}var n=Math.ceil(b/2),m=Math.floor(b/2);i.style.paddingLeft=n+PX;i.style.paddingRight=m+PX;i.style.width=l.clientWidth-b+PX;if(_rowsHeight(c,e)<k)return}}}}
function _FixedElementList(){var b=this,a=[];
b.add=function(b){a.push(b)};
b.remove=function(c){for(var b=0;b<a.length;b++)if(a[b]==c){a.splice(b,1);return}};
b.get=function(d){for(var b=0;b<a.length;b++){var c=a[b];if(c.$SOURCE_ELEMENT==d)return c}return Db};
b.getAll=function(e){for(var b=Db,c=0;c<a.length;c++){var d=a[c];if(d.$SOURCE_ELEMENT==e){if(b==Db)b=[];b.push(d)}}return b}}
function _linkElement(b,a,i,g,f){a.id&&!g&&b.removeAttribute("id");if(a.name)if(a.tagName==j&&a.type==k)b.name=RADIO_PREFIX+i+"_"+a.name;else b.removeAttribute("name");b.$SOURCE_ELEMENT=a;if(_fixedList!=Db)_fixedList.add(b);else if(!a.$FXH_FIXED_ELEMENT)a.$FXH_FIXED_ELEMENT=b;else{var h=a.$FXH_FIXED_ELEMENT;if(!h.$IS_ARRAY){var d=[];d.$IS_ARRAY=Cb;a.$FXH_FIXED_ELEMENT=d;d.push(h)}a.$FXH_FIXED_ELEMENT.push(b)}_setEventHandler(b,a);if(f)for(var c=0;c<b.childNodes.length;c++){var e=b.childNodes[c];if(!e)continue;if(!e.tagName)continue;_linkElement(e,a.childNodes[c],i,g,f)}}
function _unlinkElement(c){if(_fixedList!=Db){_fixedList.remove(c);var a=c.$SOURCE_ELEMENT;if(a&&a.$FXH_ON_CHANGE_FUNC&&_fixedList.get(a)==Db){_removeEventListener(a,g,a.$FXH_ON_CHANGE_FUNC);a.$FXH_ON_CHANGE_FUNC=undefined}}else{var a=c.$SOURCE_ELEMENT;if(a&&a.$FXH_FIXED_ELEMENT){var d=a.$FXH_FIXED_ELEMENT;if(!d.$IS_ARRAY||d.length==1){a.$FXH_FIXED_ELEMENT=undefined;if(a.$FXH_ON_CHANGE_FUNC){_removeEventListener(a,g,a.$FXH_ON_CHANGE_FUNC);a.$FXH_ON_CHANGE_FUNC=undefined}}else{for(var f=[],b=0;b<d.length;b++)d[b]!=c&&f.push(d[b]);a.$FXH_FIXED_ELEMENT=f}}}for(var b=0;b<c.childNodes.length;b++){var e=c.childNodes[b];if(!e)continue;if(!e.tagName)continue;_unlinkElement(e)}}
function _setEventHandler(b,a){if(a.onclick)b.onclick=function(){return a.onclick()};
if(a.ondblclick)b.ondblclick=function(){return a.ondblclick()};
if(a.onkeydown)b.onkeydown=function(){return a.onkeydown()};
if(a.onkeypress)b.onkeypress=function(){return a.onkeypress()};
if(a.onkeyup)b.onkeyup=function(){return a.onkeyup()};
if(a.onmousedown)b.onmousedown=function(){return a.onmousedown()};
if(a.onmouseup)b.onmouseup=function(){return a.onmouseup()};
if(a.onmouseover)b.onmouseover=function(){return a.onmouseover()};
if(a.onmouseout)b.onmouseout=function(){return a.onmouseout()};
if(a.onmousemove)b.onmousemove=function(){return a.onmousemove()};
if(a.tagName==j||a.tagName=="SELECT"||a.tagName=="TEXTAREA"){switch(a.type){case e:case f:case h:_copyValue(a,b)}switch(a.type){case h:case k:case e:case f:case "text":case i:case l:b.onclick=function(){_copyValue(b,a);_copyValues(a,b);if(a.onclick)return a.onclick();return Cb};
b.onchange=function(){_copyValue(b,a);_copyValues(a,b);if(a.onchange)return a.onchange();return Cb};
if(a.$FXH_ON_CHANGE_FUNC==undefined){a.$FXH_ON_CHANGE_FUNC=function(){_copyValues(a)};
_addEventListener(a,g,a.$FXH_ON_CHANGE_FUNC)}}}else if(a.tagName=="FORM")b.onsubmit=function(){return Bb}}
function _copyValues(d,c){if(c==undefined)c=Db;var a;if(_fixedList!=Db){a=_fixedList.getAll(d);if(!a)return;for(var b=0;b<a.length;b++){if(a[b]==c)continue;_copyValue(d,a[b])}return}a=d.$FXH_FIXED_ELEMENT;if(!a)return;if(!a.$IS_ARRAY)a!=c&&_copyValue(d,a);else for(var b=0;b<a.length;b++){if(a[b]==c)continue;_copyValue(d,a[b])}}
function _copyValue(a,b){switch(a.type){case h:case k:b.checked=a.checked;break;case e:case f:for(var c=0;c<a.length;c++)b.options[c].selected=a.options[c].selected;b.selectedIndex=a.selectedIndex;break;case "text":case i:case l:b.value=a.value;break;default:try{b.value=a.value}catch(d){}}}
function _copyStyle(src,dst,styleName){for(var buf=styleName.split(","),i=0;i<buf.length;i++){var name=_trim(buf[i]);try{eval("dst.style."+name+" = src.style."+name)}catch(e){}}}
function _setStyle(element,styleName,value){try{eval("element.style."+styleName+" = value");return Cb}catch(e){return Bb}}
function _radioCtl(d,e){for(var c=d.getElementsByTagName(j),b=0;b<c.length;b++){var a=c[b];if(a.type!=k)continue;switch(e){case "backup":a.$FXH_CHECKED=a.checked;break;case "restore":a.checked=a.$FXH_CHECKED;break;case Pb:a.checked=a.$SOURCE_ELEMENT.checked}}}
function _createCSS(c,b){var a=document.createElement("STYLE");a.setAttribute("type","text/css");a.setAttribute("media",c);if(a.styleSheet)a.styleSheet.cssText=b;else a.appendChild(document.createTextNode(b));_body.appendChild(a)}
function _getBackgroundColor(d){var e=d.currentStyle||document.defaultView.getComputedStyle(d,Hb),a=e.backgroundColor;if(a==Ob)return Db;if(a.match(/^rgba\(/)==Db)return a;var g=a.replace(/^rgba\(/,Hb).replace(/\)/,Hb),c=g.split(","),b=Number(c[3]);if(b==1)return a;var f="rgb("+_color(Number(c[0]),b)+", "+_color(Number(c[1]),b)+", "+_color(Number(c[2]),b)+")";return f}
function _color(a,b){var c=Math.round(a+(255-a)*(1-b));return Math.min(c,255)}
function _addEventListener(a,b,c){if(a.addEventListener)a.addEventListener(b,c,Bb);else a.attachEvent&&a.attachEvent("on"+b,c)}
function _removeEventListener(a,b,c){if(a.removeEventListener)a.removeEventListener(b,c,Bb);else a.detachEvent&&a.detachEvent("on"+b,c)}
function _getBodyScrollTop(){if(_isBackCompat)return document.body.scrollTop;if(_isChrome||_isSafari)return document.body.scrollTop;return document.documentElement.scrollTop}
function _getBodyScrollLeft(){if(_isBackCompat)return document.body.scrollLeft;if(_isChrome||_isSafari)return document.body.scrollLeft;return document.documentElement.scrollLeft}
function _offsetWidth(b){var a=_rect(b);return a.right-a.left}
function _offsetHeight(b){var a=_rect(b);return a.bottom-a.top}
function _rowsHeight(a,b){return _rect(a[b-1]).bottom-_rect(a[0]).top}
function _colsWidth(a,c){for(var d=0,b=0;b<a.length;b++){d+=a[b].colSpan;if(d==c){c=b+1;break}}return _rect(a[c-1]).right-_rect(a[0]).left}
function _colsWidthList(c){for(var b=Hb,a=0;a<c.length;a++){if(a>0)b+=",";b+=c[a].offsetWidth}return b}
function _rowsHeightList(c){for(var b=Hb,a=0;a<c.length;a++){if(a>0)b+=",";b+=c[a].offsetHeight}return b}
function _trHeight(a){if(_isIE8&&!_isBackCompat)return a.clientHeight;else return _offsetHeight(a)}
function _cells(g){var a=g.getElementsByTagName(Nb),b=g.getElementsByTagName("TH");if(a.length==0&&b.length==0)return a;if(a.length>0&&b.length==0)return a;if(a.length==0&&b.length>0)return b;for(var e=a[0].parentNode.childNodes,f=[],d=0;d<e.length;d++){var c=e[d];(c.tagName==Nb||c.tagName=="TH")&&f.push(c)}return f}
function _pixel(a){if(a.match(/px$/)!=Db)a=a.substring(0,a.length-2);return Number(a)}
function _percent(a){if(a.match(/%$/)!=Db)a=a.substring(0,a.length-1);return Number(a)}
function _trim(a){return a.replace(/^[ \u7e32\u0080]+/,Hb).replace(/[ \u7e32\u0080]+$/,Hb)}
function _rect(a){return a.getBoundingClientRect()}
function _getElementByTagName(b,c){var a=b.getElementsByTagName(c);if(a.length==0)return Db;return a[0]}
function _createObjectForFirefox(){var a=document.createElement("SPAN");a.style.display=Kb;a.style.position=Lb;a.style.top=Mb;a.style.left=Mb;document.body.appendChild(a);return a}
}
